using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Text;
using System.Threading.Tasks;

namespace WindowsTranslator {
public static partial class Tests
{
    private static async Task WaitForSpeech (SpeechPlayer speech, string expected)
    {
        for (int i = 0; i < 80 && speech.State != expected; i++) await Task.Delay (100);
        Check (speech.State == expected, "expected speech state " + expected + ", got " + speech.State);
    }

    private static async Task SpeechQueueIntegration ()
    {
        string fixture = Path.Combine (Path.GetTempPath (), "YikeSpeechFixture-" + Guid.NewGuid ().ToString ("N"));
        Directory.CreateDirectory (fixture);
        string wav = Path.Combine (fixture, "silence.wav");
        string script = Path.Combine (fixture, "helper.ps1");
        List<string> requests = new List<string> ();
        try {
            using (var stream = new BinaryWriter (File.Create (wav))) {
                int bytes = 16000 * 2 * 3;
                stream.Write (Encoding.ASCII.GetBytes ("RIFF")); stream.Write (36 + bytes);
                stream.Write (Encoding.ASCII.GetBytes ("WAVEfmt ")); stream.Write (16);
                stream.Write ((short)1); stream.Write ((short)1); stream.Write (16000);
                stream.Write (32000); stream.Write ((short)2); stream.Write ((short)16);
                stream.Write (Encoding.ASCII.GetBytes ("data")); stream.Write (bytes); stream.Write (new byte[bytes]);
            }
            File.WriteAllText (script, @"param([string]$JobPath,[string]$Wav)
$ErrorActionPreference='Stop'
$job=Get-Content -LiteralPath $JobPath -Raw -Encoding UTF8 | ConvertFrom-Json
for($i=0;$i -lt $job.chunks.Count;$i++) {
 if($i -gt 0){Start-Sleep -Milliseconds 4000}
 Copy-Item -LiteralPath $Wav -Destination (Join-Path $job.folder ($i.ToString()+'.wav'))
 [Console]::Out.WriteLine('READY '+$i);[Console]::Out.Flush()
}
", Encoding.UTF8);
            using (var speech = new SpeechPlayer (0, delegate(string job, bool online) {
                requests.Add (Path.GetDirectoryName (job));
                return new ProcessStartInfo {
                    FileName = Path.Combine (Environment.GetFolderPath (Environment.SpecialFolder.System), "WindowsPowerShell\\v1.0\\powershell.exe"),
                    Arguments = "-NoProfile -NonInteractive -ExecutionPolicy Bypass -File \"" + script + "\" -JobPath \"" + job + "\" -Wav \"" + wav + "\"",
                    UseShellExecute = false, CreateNoWindow = true, RedirectStandardOutput = true, RedirectStandardError = true
                };
            })) {
                string error = null;
                speech.Failed += message => error = message;
                Task generating = speech.Speak (new string ('x', 200), "EN-US", "female", 0, false);
                await WaitForSpeech (speech, "playing");
                Check (speech.IsGenerating, "first audio waited for deliberately delayed later synthesis");
                await Task.Delay (200);
                speech.TogglePause ();
                TimeSpan frozen = speech.Position;
                await generating;
                Check (speech.State == "paused" && Math.Abs ((speech.Position - frozen).TotalMilliseconds) < 80, "prefetch resumed paused audio");
                speech.TogglePause ();
                for (int i = 0; i < 80 && speech.Position.TotalSeconds <= 3 && speech.State != "idle"; i++) await Task.Delay (100);
                Check (error == null && speech.State == "playing" && speech.Position.TotalSeconds > 3, "second segment failed or playback position reset: state=" + speech.State + ", position=" + speech.Position + ", error=" + error);
                await WaitForSpeech (speech, "idle");
                Task canceled = speech.Speak (new string ('y', 200), "EN-US", "female", 0, false);
                await WaitForSpeech (speech, "playing");
                Task replacement = speech.Speak ("Replacement request.", "EN-US", "female", 0, false);
                await replacement;
                await canceled;
                await WaitForSpeech (speech, "playing");
                Check (error == null, "canceled synthesis affected replacement: " + error);
                speech.Stop ();
                Check (speech.State == "idle", "stop did not clear the segment queue");
            }
            Check (requests.TrueForAll (request => !Directory.Exists (request)), "temporary speech text or audio was retained after stop");
        } finally {
            // The fixture path above is generated by this test, under the temp root.
            Directory.Delete (fixture, true);
        }
    }
}
}
